// src/lib/i18n/locales/en/about.ts
export const aboutTranslations = {
  title: 'About AI Trainer',
  aboutApp: 'About This App',
  appDescription: 'AI Trainer is an innovative application designed to help you achieve your fitness goals through personalized workout and nutrition plans. Our AI-powered platform creates customized fitness routines and meal plans tailored to your specific needs, preferences, and goals. Since I use the free plans of the Gemini API, the application’s performance may be slow and sometimes throw errors due to reaching the daily usage quota.',
  aboutMe: 'About Me',
  myDescription: 'Hello! My name is Marlon Bochi. I\'m a developer and enthusiast who created this app to help combine technology and health. My goal is to make fitness accessible and personalized for everyone, using the power of AI to create effective training and nutrition plans.',
  importantNote: 'Important Note',
  disclaimer: 'The information provided by this app is for general informational purposes only and is not intended as medical or professional advice. The workout and nutrition plans generated by this app are based on AI algorithms and may not be suitable for everyone. Always consult with a qualified healthcare professional before starting any new exercise or nutrition program. The creator of this app is not responsible for any injuries, health issues, or other problems that may result from using the information or recommendations provided by this application.',
  howItWorks: 'How It Works',
  step1Title: 'Set Your Goals',
  step1Desc: 'Tell us about your fitness goals, preferences, and any dietary restrictions.',
  step2Title: 'Get Your Plan',
  step2Desc: 'Our AI generates a personalized workout and nutrition plan just for you.',
  step3Title: 'Track & Improve',
  step3Desc: 'Follow your plan, track your progress, and adjust as needed.',
  connectWithMe: 'Connect with me on social media'
};
